import type { Metadata } from "next";
import "@/app/ui/globals.css"
import { comfortaa } from "./ui/fonts";


export const metadata: Metadata = {
  title: "Family Photo Gallery",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={comfortaa.className}>{children}</body>
    </html>
  );
}
